// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gomem/mservices/engine/engine.proto

package engine

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *MessageResponse) Validate() error {
	return nil
}
