version: '3.8'

services:
#  server:
#    build: .
#    restart: on-failure
#    ports:
#      - 5000:5000
#    environment:
#      MONGO_USERNAME: root
#      MONGO_PASSWORD: root
  mongo:
    image: mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root